version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - PORT=5432
    networks:
      - jobsSubnetwork

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - jobsSubnetwork

networks:
  jobsSubnetwork:
